<!DOCTYPE html>
<html lang="ja" class="">

<head>
  <meta charset="utf-8">
  <title><?php echo $page_title ?> - お問い合わせ｜テストページ</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="robots" content="noimageindex, noarchive">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="mobile-web-app-capable" content="yes">
  <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">
  <meta name="description" content="" />
  <link href="/inquiry/assets/css/style.css" rel="stylesheet" />
</head>

<body>
  <div class="wrapper">
    <header class="header">
      <h1 class="header__title">
        お問い合わせ
      </h1>
    </header>