<!DOCTYPE html>
<html lang="ja" class="">

<head>
  <meta charset="utf-8">
  <title><?php echo $page_title ?> - お問い合わせ｜テストページ</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="robots" content="noimageindex, noarchive">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="mobile-web-app-capable" content="yes">
  <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">
  <meta name="description" content="" />
  <?php /*
<link href="/assets/css/ress.min.css" rel="stylesheet" />
<link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
<link href="/assets/css/common.css" rel="stylesheet" />
<link href="/assets/css/form.css" rel="stylesheet" />
<link rel="shortcut icon" type="image/x-icon" href="/assets/images/favicon/favicon.ico">
<link rel="alternate" href="" hreflang="x-default" />
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-TSCQ333');</script>
*/ ?>
</head>

<body>
  <div class="wrapper">
    <header class="header">
      <h1 class="header__title">
        お問い合わせ
      </h1>
    </header>